"""
brain/action_candidate.py

Represents a candidate action generated by the AI.
"""

from dataclasses import dataclass
from typing import Any


@dataclass(slots=True)
class ActionCandidate:
    """
    Represents one possible action considered by the AI.
    """

    action: Any

    task: str

    target: Any = None

    priority: int = 0

    score: float = 0.0

    estimated_profit: float = 0.0

    distance: int = 0

    worker_id: int | None = None

    reason: str = ""

    metadata: dict[str, Any] | None = None

    @property
    def final_score(self) -> float:
        """
        Final score after penalties.
        """

        return self.score - self.distance

    def add_reason(self, reason: str):

        if self.reason:

            self.reason += " | "

        self.reason += reason

    def __repr__(self):

        return (
            f"ActionCandidate("
            f"task={self.task}, "
            f"score={self.score:.2f}, "
            f"distance={self.distance})"
        )